In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv')

In [3]:
df

      Name  Age  Grade      City
0    Alice   20     85    Boston
1      Bob   19     92  New York
2  Charlie   21     78   Chicago
3    Diana   20     88    Boston
4      Eve   22     95   Seattle
5    Frank   19     82     Miami
6    Grace   21     90    Denver
7    Henry   20     76    Austin
8     Iris   22     89  Portland
9     Jack   19     84   Phoenix

In [4]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [5]:
df = pd.read_excel('Sales_Data.xlsx', sheet_name = 'January')

In [6]:
df

          Date Region  Product  Units_Sold  Revenue    Month
0   2025-01-01   East   Laptop          33  1185.47  January
1   2025-01-02   West   Tablet          39  2737.15  January
2   2025-01-03   West    Phone          25  2281.43  January
3   2025-01-04   East    Phone          32  1762.67  January
4   2025-01-05  North   Tablet          34  2148.43  January
5   2025-01-06   West    Phone          16   896.24  January
6   2025-01-07  South    Phone          35  2252.04  January
7   2025-01-08  South   Laptop           2  3356.70  January
8   2025-01-09  North   Laptop          19  2541.82  January
9   2025-01-10  North   Laptop          23   984.60  January
10  2025-01-11   West    Phone           7  3091.30  January
11  2025-01-12   East   Laptop          40   994.27  January
12  2025-01-13  South   Tablet           8  4659.21  January
13  2025-01-14   East  Monitor           2  4697.84  January
14  2025-01-15   East  Monitor          15  3393.65  January
15  2025-01-16   East  Monitor          13  3347.45  January
16  2025-01-17   East   Tablet           5   517.22  January
17  2025-01-18   West   Laptop          50  4059.23  January
18  2025-01-19   West  Monitor          34  1980.08  January
19  2025-01-20   West   Tablet          31  1222.49  January